# Generated by Django 4.0.1 on 2022-02-01 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0002_edificacion_empresa_delete_inmueble'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edificacion',
            old_name='create',
            new_name='created',
        ),
        migrations.AddField(
            model_name='edificacion',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='edificaciones', to='inmuebleslist_app.empresa'),
            preserve_default=False,
        ),
    ]
